[agent]
  interval = "30s"
  flush_interval = "30s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["zigbee2mqtt/#"]
  data_format = "json"
  name_override = "zigbee_device"
  topic_tag = "device"

[[processors.regex]]
  namepass = ["zigbee_device"]

  [[processors.regex.tags]]
    key = "device"
    pattern = "^zigbee2mqtt/aqara_.*$"
    replacement = "weather"
    result_key = "target_bucket"

  [[processors.regex.tags]]
    key = "device"
    pattern = "^zigbee2mqtt/plug_.*$"
    replacement = "power"
    result_key = "target_bucket"

[[outputs.influxdb_v2]]
  alias = "influx_weather"
  urls = ["http://influxdb:8086"]
  token = "<TOKEN>"
  organization = "home"
  bucket = "weather"
  tagexclude = ["target_bucket"]

  [outputs.influxdb_v2.tagpass]
    target_bucket = ["weather"]

[[outputs.influxdb_v2]]
  alias = "influx_power"
  urls = ["http://influxdb:8086"]
  token = "<TOKEN>"
  organization = "home"
  bucket = "power"
  tagexclude = ["target_bucket"]

  [outputs.influxdb_v2.tagpass]
    target_bucket = ["power"]
