services:
  emushpedia-archives:
    image: nginx:stable-alpine
    container_name: ${COMPOSE_ENV}
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ../live/${COMPOSE_ENV}/nginx/conf.d:/etc/nginx/conf.d:ro
      - ../live/${COMPOSE_ENV}/downloads/:/var/www/downloads:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.${COMPOSE_ENV}.rule=${TRAEFIK_RULE}"
      - "traefik.http.routers.${COMPOSE_ENV}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_ENV}.tls=true"
      - "traefik.http.routers.${COMPOSE_ENV}.tls.certresolver=letsencrypt"

      - "traefik.http.services.${COMPOSE_ENV}.loadbalancer.server.port=80"
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  web:
    external: true
    name: web
