services:
  filebrowser:
    image: gtstef/filebrowser:stable
    container_name: ${COMPOSE_ENV}-filebrowser
    user: 1000:1000  # filebrowser user in the container
    env_file: "../live/${COMPOSE_ENV}/.env"
    volumes:
      - ../live/${COMPOSE_ENV}/folder:/folder
      - ../live/${COMPOSE_ENV}/conf:/home/filebrowser/data
    restart: unless-stopped
    networks:
      - web

  filebrowser-nginx:
    image: nginx:stable-alpine
    container_name: ${COMPOSE_ENV}-nginx
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ../live/${COMPOSE_ENV}/nginx/conf.d:/etc/nginx/conf.d:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.${COMPOSE_ENV}.rule=${TRAEFIK_RULE}"
      - "traefik.http.routers.${COMPOSE_ENV}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_ENV}.tls=true"
      - "traefik.http.routers.${COMPOSE_ENV}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${COMPOSE_ENV}.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
    name: web
